dist: xenial

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - which pip
  - pip --version
  - which python3
  - python3 --version
  - pip3 --version || true
  - python3 -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo -H python3
  - python3 -m pip install --user awscli
  - which aws
script: aws --version
