env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - python --version ; python2 --version ; python3 --version
  - pip --version    ; pip2 --version
  - pip3 --version || true
  - which pip
  - which python3
  - python3 -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo -H python3
  - python3 -m pip --version
  - python3 -m pip install --user awscli
  - which aws
script: aws --version
